*IMPOTANDO LIBRERIA NUMPY*

In [ ]:
import numpy as np

*Creando una lista de 10 elementos*

In [19]:
lista=list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

*TRANSFORMANDO LISTA A ARREGLO*

In [ ]:
arreglo=np.array(lista)
arreglo

*CORROBORANDO EL TIPO DE ESTRUCTURA*

In [ ]:
type(arreglo)

*COMPROBANDO EL TIPO DE DATOS DEL ARREGLO*

In [ ]:
arreglo.dtype

*DEFINIENDO EL ARRAY DE int32 A float32*

In [ ]:
np.array(arreglo, dtype=np.float32)

#### **Sigue siendo una array de int32**

In [17]:
type(arreglo)

numpy.ndarray

*Transformando los datos de int32 a float32*

In [18]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

*Arreglo de 10 elementos de solo unos*

In [21]:
arreglo_de_unos=np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

*Transformando el arreglo de unos a punto flotante*

## **UTILIZANDO LA FUNDION RANDOM**

In [23]:
arreglo_aleatorio=np.random.rand(5)
arreglo_aleatorio

array([0.50880875, 0.23656269, 0.21960645, 0.57755052, 0.90536194])

### *Generando una matriz aleatoria de 3x3*

In [24]:
matriz=np.random.rand(3,3)
matriz

array([[0.97732952, 0.32372358, 0.70560055],
       [0.7997384 , 0.14653112, 0.8838449 ],
       [0.83168408, 0.65934558, 0.28983689]])

###  *Generando un arreglo aleatorio de 10 nunmeros enteros del 1 al 5*

In [25]:
arreglo_aleatorio2=np.random.randint(1,5,10)
arreglo_aleatorio2

array([4, 4, 2, 1, 1, 2, 1, 4, 4, 3])

### *Generando una matriz aleatoria de 10 numeros enteros del 1 al 100*

In [32]:
matriz2=np.random.randint(1,100,100)
matriz2

array([81,  2, 35, 85, 20, 69, 12,  6, 65, 16, 94, 85, 72, 65, 71, 64, 31,
       28, 20,  4, 38, 10, 41, 27, 22, 17, 56, 49, 55, 20, 31, 58, 28, 96,
       32, 25, 21, 37, 13, 99, 57, 17,  3, 22, 91, 53, 24,  8, 41, 42, 26,
       66, 28,  7, 19, 63, 46, 56, 76, 83, 95, 60, 21, 48,  9, 44, 99, 20,
       72, 94, 69, 80, 84, 89,  6, 34,  1, 43, 16, 83, 89, 19, 75, 91, 84,
       89, 68,  6, 26, 42, 52, 99, 25, 47, 54, 88, 36, 27, 97, 78])